# ===============================================================
# 根据如下的配置说明完善自己的站点配置，建议另外拷贝进行调整避免冲突
# Improve your site configuration according to the following 
# configuration instructions. It is recommended to make 
# additional copies for adjustment to avoid conflicts
# ===============================================================

# ---------------------------------------------------------------
# Hugo 引擎的基础配置
# Basic configure for Hugo engine 
# ---------------------------------------------------------------

# 站点域名，比如： https://hugo-next.eu.org
# Website domain, eg: https://hugo-next.eu.org
baseURL: /

# Website title
title: Nate's Blog

# Theme name
theme: hugo-theme-next

# Default laguage & code for website
defaultContentLanguage: en
languageCode: en

# Whether contains Chinese, Japanese and Korean
hasCJKLanguage: true

# Display items per page
paginate: 10

# Enable Emoji support
enableEmoji: true

# Make markdown content support HTML syntax, highlight, toc etc.
markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    # codeFences: true
    # lineNos: true
    # lineNumbersInTable: true
    # noClasses: true

    # # Highlight style: monokai | emacs | api | dracula | friendly
    # # More: https://xyproto.github.io/splash/docs/all.html 
    # style: "monokai"
    anchorLineNos: true
    codeFences: true
    guessSyntax: true
    hl_Lines: ""
    hl_inline: false
    lineAnchors: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: false
    noClasses: true
    noHl: false
    style: monokai
    tabWidth: 2
  tableOfContents:

    # Heading title level of start or end: 1-6
    # Recommand start at 2
    startLevel: 2
    endLevel: 4

# 站点文章导航文件
# Site map of all articles
sitemap:
  filename: "sitemap.xml"
  changefreq: "weekly"
  priority: 0.5

outputFormats:
  RSS:
    baseName: "rss"

  # Custom file of indexes for local search
  LocalIndexes:
    mediaType: application/xml
    baseName: searchindexes
    isPlainText: true
    notAlternative: true

  # Build indexes of Aloglia
  AlgoliaIndexes:
    mediaType: application/json
    baseName: algolia
    isPlainText: true
    notAlternative: true

# 默认使用本地搜索，如切换到 Algolia 搜索引擎，
# 请将下面的 LocalIndexes 替换成 AlgoliaIndexes
# By default use local search, before switch to Algolia engine
# Please replace LocalIndexes with AlgoliaIndexes
outputs:
  home: ["HTML", "RSS", "LocalIndexes"]

# 输出 robots 文件支持爬虫扫描
# Enable robots with support crawler scan
enableRobotsTXT: true

# 强制输出时压缩文件
# Compress all files when output
minify:
  minifyOutput: true
  
